import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  id: {
    // Common
    'app.name': 'PDAM Seruyan',
    'app.management': 'Badan Usaha Milik Daerah',
    'common.logout': 'Keluar',
    'common.search': 'Cari...',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.history': 'Riwayat',
    'common.back': 'Kembali',
    'common.next': 'Lanjut',
    'common.details': 'Detail',
    'common.yesterday': 'Kemarin',
    'common.urgent': 'Mendesak',
    'common.status': 'Status',
    'common.priority': 'Prioritas',
    'common.action': 'Tindakan',

    // Months
    'month.01': 'Januari',
    'month.02': 'Februari',
    'month.03': 'Maret',
    'month.04': 'April',
    'month.05': 'Mei',
    'month.06': 'Juni',
    'month.07': 'Juli',
    'month.08': 'Agustus',
    'month.09': 'September',
    'month.10': 'Oktober',
    'month.11': 'November',
    'month.12': 'Desember',
    'month.short.01': 'Jan',
    'month.short.02': 'Feb',
    'month.short.03': 'Mar',
    'month.short.04': 'Apr',
    'month.short.05': 'Mei',
    'month.short.06': 'Jun',

    // Login & Gate
    'login.title': 'Selamat Datang Kembali',
    'login.subtitle': 'Kelola akun PDAM Seruyan Anda dengan mudah dan aman.',
    'login.gate.title': 'Pilih Portal Akses',
    'login.gate.subtitle': 'Silakan pilih identitas Anda untuk melanjutkan ke dashboard yang sesuai.',
    'login.role.admin.title': 'Dashboard Administrator',
    'login.role.admin.desc': 'Kelola infrastruktur, penagihan, dan koordinasi tim lapangan.',
    'login.role.staff.title': 'Portal Petugas Lapangan',
    'login.role.staff.desc': 'Akses perintah kerja, pelaporan meter, dan pemeliharaan teknis.',
    'login.role.user.title': 'Portal Pelanggan',
    'login.role.user.desc': 'Cek tagihan mandiri, riwayat pemakaian, dan lapor keluhan.',
    'login.label.identity': 'Username, Email, atau No. WhatsApp',
    'login.placeholder.identity': 'nama_user atau nama@email.com',
    'login.label.password': 'Kata Sandi',
    'login.label.remember': 'Ingat saya',
    'login.label.forgot': 'Lupa kata sandi?',
    'login.button.signin': 'Masuk Sekarang',

    'login.button.back_role': 'Kembali ke Pemilihan Peran',
    'login.footer.back': 'Kembali ke Gerbang Utama',
    'login.verify.title': 'Verifikasi Akun Petugas',
    'login.verify.subtitle': 'Silakan masukkan 6 digit kode yang dikirimkan Admin ke WhatsApp/Email Anda.',
    'login.verify.button': 'Verifikasi & Masuk',
    'login.verify.label': 'Kode Verifikasi',
    'login.verify.footer': 'Pendaftaran petugas memerlukan persetujuan manual dari Administrator PDAM.',
    'login.reset.email_sent': 'Instruksi pemulihan telah dikirim ke email Anda. Silakan cek kotak masuk Anda.',
    'login.reset.success': 'Kata sandi berhasil diperbarui! Silakan masuk dengan kata sandi baru Anda.',
    'login.reset.new_password': 'Buat Kata Sandi Baru',
    'login.reset.confirm_button': 'Simpan Kata Sandi',
    'login.reset.subtitle': 'Silakan masukkan kata sandi baru untuk mengamankan akun Anda.',
    'login.reset.back': 'Kembali ke Halaman Masuk',
    'login.error.pending': 'Akun Anda belum aktif. Harap tunggu aktivasi oleh Administrator.',
    'login.error.blocked': 'Akun Anda telah dinonaktifkan. Silakan hubungi Administrator.',
    'login.pending.title': 'Harap Tunggu Aktivasi',
    'login.pending.subtitle': 'Akun Anda sedang dalam proses verifikasi oleh Administrator. Mohon tunggu informasi selanjutnya atau hubungi bagian IT kami.',
    'login.pending.button': 'Kembali ke Gerbang Utama',

    // Admin Dashboard
    'admin.profile.role': 'Administrator Sistem',
    'admin.sidebar.dashboard': 'Ringkasan',
    'admin.sidebar.waterflow': 'Monitoring Aliran',
    'admin.sidebar.billing': 'Tagihan & Pelanggan',
    'admin.sidebar.tasks': 'Perintah Kerja',
    'admin.stats.total_customers': 'Total Pelanggan',
    'admin.stats.active_staff': 'Petugas Aktif',
    'admin.stats.task_orders': 'Perintah Kerja',
    'admin.stats.active_online': 'Petugas Online',
    'admin.stats.pending_tasks': 'Menunggu Eksekusi',
    'admin.stats.vs_last_month': 'vs bulan lalu',
    'admin.stats.from_last_month': 'dari bulan lalu',

    'admin.user.management': 'Manajemen Pengguna',
    'admin.user.management_sub': 'Kelola hak akses dan verifikasi personel lapangan.',
    'admin.activity.tariff_update': 'Pembaruan tarif dikirim ke Bak Selatan',
    'admin.activity.tariff_desc': 'Admin Alex Seruyan menyesuaikan tarif volumetrik sebesar +2% untuk meteran industri.',
    'admin.activity.new_staff': 'Petugas Lapangan baru telah didaftarkan',
    'admin.activity.staff_desc': 'Siti Rahayu diberikan akses ke konfigurasi regional Bak Utara dan tiket perbaikan.',
    'admin.user.table.name': 'Nama Lengkap',
    'admin.user.table.whatsapp': 'WhatsApp',
    'admin.user.table.role': 'Peran',
    'admin.user.table.code': 'Kode Verifikasi',
    'admin.user.table.actions': 'Tindakan',
    'admin.user.details': 'Detail Profil',
    'admin.user.table.identity': 'Identitas Akun',
    'admin.user.table.contact': 'Kontak Personel',
    'admin.user.table.password': 'Kata Sandi',
    'admin.user.table.role_status': 'Peran & Status',
    'admin.user.table.v_actions': 'Aksi Verifikasi',
    'admin.user.add_new': 'Tambah Akun Baru',
    'admin.user.msg.added': 'Berhasil menambahkan pengguna',
    'admin.user.msg.status_updated': 'Status pengguna berhasil diperbarui',
    'admin.user.msg.status_error': 'Gagal memperbarui status pengguna',
    'admin.user.button.activate': 'Aktifkan Akun',
    'admin.user.button.deactivate': 'Nonaktifkan Akun',

    'admin.tasks.management': 'Daftar Perintah Kerja',
    'admin.tasks.management_sub': 'Monitoring dan penugasan tim lapangan secara real-time.',
    'admin.tasks.table.details': 'Detail Pekerjaan',
    'admin.tasks.table.reason': 'Uraian / Prioritas',
    'admin.tasks.table.assignee': 'Personel',
    'admin.tasks.table.status': 'Status',
    'admin.tasks.table.actions': 'Aksi',
    'admin.tasks.empty': 'Tidak ada perintah kerja yang aktif',
    'admin.tasks.routine': 'Pemeliharaan Berkala',
    'admin.tasks.unknown_staff': 'Petugas Belum Ada',
    'admin.tasks.unknown_customer': 'Pelanggan Tidak Terdaftar',
    'admin.tasks.unassigned_tag': 'Belum Ditugaskan',
    'admin.tasks.deadline.urgent': 'Deadline 24 Jam',
    'admin.tasks.deadline.cycle': 'Jadwal Siklus',

    'admin.sidebar.requests': 'Permohonan Baru',
    'admin.requests.title': 'Permohonan Baru',
    'admin.requests.subtitle': 'Tinjau dan proses pendaftaran pelanggan baru.',
    'admin.requests.table.details': 'Detail Pemohon',
    'admin.requests.table.contact': 'Kontak',
    'admin.requests.table.date': 'Tanggal Masuk',
    'admin.requests.table.status': 'Status',
    'admin.requests.table.actions': 'Tindakan',
    'admin.requests.empty': 'Tidak ada permohonan tertunda.',
    'admin.requests.status.pending': 'Tertunda',
    'admin.requests.status.approved': 'Disetujui',
    'admin.requests.status.rejected': 'Ditolak',
    'admin.requests.approve': 'Setujui',
    'admin.requests.reject': 'Tolak',

    // Admin Sub-components
    'admin.waterflow.title': 'Monitoring Aliran Air',
    'admin.waterflow.subtitle': 'Analisis distribusi dan tekanan real-time di setiap sektor.',
    'admin.waterflow.total': 'Total Output Sistem',
    'admin.waterflow.stable': 'Aliran Stabil',
    'admin.waterflow.flow': 'Debit Aliran',
    'admin.waterflow.pressure': 'Tekanan Jalur',
    'admin.waterflow.zone.north': 'Bak Penampungan Utara',
    'admin.waterflow.zone.central': 'Distrik Pusat',
    'admin.waterflow.zone.west': 'Sektor Barat',
    'admin.waterflow.zone.south': 'Kawasan Industri Selatan',

    'admin.billing.title': 'Tagihan & Pendapatan',
    'admin.billing.subtitle': 'Kelola transaksi keuangan dan siklus penagihan pelanggan.',
    'admin.billing.monthly': 'Pendapatan Bulan Ini',
    'admin.billing.recent': 'Transaksi Terkini',
    'admin.billing.filter': 'Filter Data',

    // Admin Modals
    'admin.user.add_title': 'Buat Akun Baru',
    'admin.user.verified': 'Sudah Terverifikasi',
    'admin.user.label.name': 'Nama Lengkap',
    'admin.user.label.email': 'Alamat Email',
    'admin.user.label.phone': 'Nomor WhatsApp',
    'admin.user.label.password': 'Kata Sandi Awal',
    'admin.user.label.role': 'Peran Sistem',
    'admin.user.role.customer': 'Pelanggan',
    'admin.user.role.staff': 'Staf Petugas',
    'admin.user.button.cancel': 'Batalkan',
    'admin.user.button.create': 'Konfirmasi Buat Akun',
    'admin.user.button.creating': 'Memproses...',

    'admin.tasks.not_found': 'Pekerjaan tidak ditemukan',
    'admin.tasks.status.unassigned': 'Menunggu Penugasan',
    'admin.tasks.priority.high': 'Prioritas Tinggi',
    'admin.tasks.priority.normal': 'Prioritas Normal',
    'admin.tasks.status.pending': 'Tertunda',
    'admin.tasks.status.assigned': 'Telah Ditugaskan',
    'admin.tasks.status.completed': 'Selesai Terverifikasi',
    'admin.tasks.status.active': 'Sedang Dikerjakan',
    'admin.tasks.add': 'Tambah Perintah Kerja',

    'admin.tasks.add_title': 'Buat Perintah Kerja Baru',
    'admin.tasks.label.type': 'Kategori Pekerjaan',
    'admin.tasks.label.customer': 'Data Pelanggan',
    'admin.tasks.label.location': 'Lokasi Penugasan',
    'admin.tasks.label.district': 'Distrik / Zona',
    'admin.tasks.label.priority': 'Level Prioritas',
    'admin.tasks.label.staff': 'Pilih Petugas (Opsional)',
    'admin.tasks.label.reason': 'Catatan / Alasan',
    'admin.tasks.placeholder.location': 'misal: Jl. Merdeka No. 5',
    'admin.tasks.placeholder.district': 'misal: Seruyan Hilir',
    'admin.tasks.placeholder.reason_disconnect': 'misal: Tunggakan lebih dari 3 bulan',
    'admin.tasks.placeholder.reason_leak': 'misal: Laporan kebocoran pipa utama',
    'admin.tasks.type.repair': 'Perbaikan Teknik',
    'admin.tasks.type.repair_prefix': 'Perbaikan:',
    'admin.tasks.type.reading': 'Bacameter / Pemasangan',
    'admin.tasks.type.reading_prefix': 'Meteran:',
    'admin.tasks.type.disconnection': 'Pemutusan Sambungan',
    'admin.tasks.type.disconnection_prefix': 'Pencabutan:',
    'admin.tasks.type.new_connection': 'Penyambungan Baru',
    'admin.tasks.type.new_connection_prefix': 'Sambung Baru:',
    'admin.tasks.select_customer': 'Cari Pelanggan...',
    'admin.tasks.unassigned': 'Tangguhkan Penugasan',

    // Staff Dashboard
    'staff.stats.today': 'Hari Ini',
    'staff.tasks.queue.repair': 'Antrean Perbaikan',
    'staff.tasks.queue.reading': 'Jadwal Pemasangan/Baca',
    'staff.tasks.queue.disconnection': 'Daftar Pemutusan',
    'staff.tasks.work_orders': 'Perintah Kerja',
    'staff.tasks.priority_tag': 'Prioritas',
    'staff.tasks.id': 'Nomor ID',
    'staff.tasks.verify_meter': 'Verifikasi No. Meter {id}',
    'staff.tasks.warning_resident': 'Berikan teguran akhir ke penghuni',
    'staff.tasks.cycle.planned': 'Siklus Terjadwal',
    'staff.tasks.deadline.by': 'Selesaikan Sebelum',
    'staff.tasks.button.start': 'Mulai Pekerjaan',
    'staff.tasks.empty.reading': 'Tidak ada jadwal baca meter tersisa',
    'staff.tasks.empty.generic': 'Belum ada tugas di kategori ini',
    'staff.tasks.sop.title': 'Prosedur Operasional (SOP)',
    'staff.tasks.sop.subtitle': 'Update Protokol Keamanan V.2',

    'staff.tabs.repair': 'Perbaikan',
    'staff.tabs.reading': 'Meter/Pasang',
    'staff.tabs.disconnection': 'Pemutusan',
    'staff.tabs.new_connection': 'Sambungan Baru',
    'staff.tasks.queue.new_connection': 'Antrean Sambungan Baru',
    'staff.stats.daily_target': 'Kapasitas Tugas',
    'staff.stats.completed': 'Tuntas',
    'staff.stats.pending': 'Menunggu',
    'staff.tasks.manual_reading': 'Input Meteran Baru',
    'staff.profile.sector': 'Sektor Seruyan',

    // Staff Reporting
    'staff.reading.title': 'Input Baca Meter',
    'staff.reading.subtitle.assigned': 'Melaporkan penugasan rutin.',
    'staff.reading.subtitle.manual': 'Input mandiri di lokasi pelanggan.',
    'staff.reading.search': 'Cari Nama atau ID Pelanggan...',
    'staff.reading.success.title': 'Data Tercatat!',
    'staff.reading.success.subtitle': 'Angka meteran {name} berhasil dikirim ke server.',
    'staff.reading.previous': 'Angka Sebelumnya',
    'staff.reading.current': 'Angka Terkini',
    'staff.reading.capture': 'Ambil Foto Meteran',
    'staff.reading.submit': 'Kirim Laporan',
    'staff.reading.uploading': 'Mengirim...',

    'staff.disconnection.title': 'Eksekusi Pemutusan',
    'staff.disconnection.verify': 'Verifikasi Tugas',
    'staff.disconnection.checklist': 'Pengecekan Lapangan',
    'staff.disconnection.button.continue': 'Lanjut ke Pemutusan Fisik',
    'staff.disconnection.action.title': 'Tindakan Teknis',
    'staff.disconnection.action.subtitle': 'Lakukan penyegelan dan pengangkatan meteran pelanggan.',
    'staff.disconnection.proof': 'Foto Segel & Meteran',
    'staff.disconnection.notes': 'Catatan Petugas (Opsional)',
    'staff.disconnection.submit': 'Kirim Dokumentasi',
    'staff.disconnection.confirm.title': 'Konfirmasi Akhir',
    'staff.disconnection.confirm.subtitle': 'Laporan akan dikirim secara permanen ke sistem.',
    'staff.disconnection.button.finalize': 'Finalisasi Tugas',
    'staff.disconnection.success.title': 'Tugas Selesai!',
    'staff.disconnection.success.subtitle': 'Pemutusan untuk {name} telah diverifikasi.',
    'staff.disconnection.return': 'Kembali ke Beranda',
    'staff.reading.prev': 'Pembacaan Sebelumnya',
    'staff.reading.curr': 'Pembacaan Sekarang',
    'staff.reading.proof': 'Bukti Visual / Foto',

    // User Portal
    'user.balance.title': 'Tagihan Berjalan',
    'user.balance.due': 'Jatuh Tempo',
    'user.balance.pay': 'Bayar Sekarang',
    'user.stats.usage': 'Pemakaian',
    'user.stats.efficiency': 'Efisiensi',
    'user.tabs.history': 'Riwayat Tagihan',
    'user.tabs.analysis': 'Analisis Konsumsi',
    'user.billing.recent': 'Tagihan Terakhir',
    'user.billing.view_all': 'Lihat Semua Riwayat',
    'user.billing.download': 'Unduh Invoice (PDF)',
    'user.usage.trend': 'Tren Konsumsi Air',
    'user.usage.ytd': 'Total Konsumsi (Tahun Ini)',
    'user.support.leak': 'Lapor Kebocoran Pipa',
    'user.support.emergency': 'Bantuan darurat teknis 24/7',
    'user.bill.unit': 'm³',
    'user.bill.usage_label': 'Pemakaian:',
  },
  en: {
    // Common
    'app.name': 'Seruyan Utility',
    'app.management': 'Regional-Owned Enterprise',
    'common.logout': 'Logout',
    'common.search': 'Search...',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.history': 'History',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.details': 'Details',
    'common.yesterday': 'Yesterday',
    'common.urgent': 'Urgent',
    'common.status': 'Status',
    'common.priority': 'Priority',
    'common.action': 'Action',

    // Months
    'month.01': 'January',
    'month.02': 'February',
    'month.03': 'March',
    'month.04': 'April',
    'month.05': 'May',
    'month.06': 'June',
    'month.07': 'July',
    'month.08': 'August',
    'month.09': 'September',
    'month.10': 'October',
    'month.11': 'November',
    'month.12': 'December',
    'month.short.01': 'Jan',
    'month.short.02': 'Feb',
    'month.short.03': 'Mar',
    'month.short.04': 'Apr',
    'month.short.05': 'May',
    'month.short.06': 'Jun',

    // Login & Gate
    'login.title': 'Welcome Back',
    'login.subtitle': 'Manage your Seruyan PDAM account easily and securely.',
    'login.gate.title': 'Select Access Portal',
    'login.gate.subtitle': 'Please choose your identity to proceed to the relevant dashboard.',
    'login.role.admin.title': 'Administrator Dashboard',
    'login.role.admin.desc': 'Manage infrastructure, billing, and field team coordination.',
    'login.role.staff.title': 'Field Staff Portal',
    'login.role.staff.desc': 'Access work orders, meter reporting, and technical maintenance.',
    'login.role.user.title': 'Customer Portal',
    'login.role.user.desc': 'Check bills, usage history, and report issues.',
    'login.label.identity': 'Username, Email, or WhatsApp',
    'login.placeholder.identity': 'username or name@email.com',
    'login.label.password': 'Password',
    'login.label.remember': 'Remember me',
    'login.label.forgot': 'Forgot password?',
    'login.button.signin': 'Sign In Now',

    'login.button.back_role': 'Return to Role Selection',
    'login.footer.back': 'Back to Main Gate',
    'login.verify.title': 'Staff Verification',
    'login.verify.subtitle': 'Please enter the 6-digit code sent by Admin to your WhatsApp/Email.',
    'login.verify.button': 'Verify & Sign In',
    'login.verify.label': 'Verification Code',
    'login.verify.footer': 'Staff registration requires manual approval from the PDAM Administrator.',
    'login.reset.email_sent': 'Recovery instructions have been sent to your email. Please check your inbox.',
    'login.reset.success': 'Password updated successfully! Please log in with your new password.',
    'login.reset.new_password': 'Create New Password',
    'login.reset.confirm_button': 'Update Password',
    'login.reset.subtitle': 'Please enter a new password to secure your account.',
    'login.reset.back': 'Return to Login',
    'login.error.pending': 'Your account is not active yet. Please wait for Administrator activation.',
    'login.error.blocked': 'Your account has been deactivated. Please contact the Administrator.',
    'login.pending.title': 'Awaiting Activation',
    'login.pending.subtitle': 'Your account is currently being verified by the Administrator. Please wait for further information or contact the IT department.',
    'login.pending.button': 'Back to Main Gate',

    // Admin Dashboard
    'admin.profile.role': 'System Administrator',
    'admin.sidebar.dashboard': 'Overview',
    'admin.sidebar.waterflow': 'Water Monitoring',
    'admin.sidebar.billing': 'Billing & Members',
    'admin.sidebar.tasks': 'Work Orders',
    'admin.stats.total_customers': 'Total Customers',
    'admin.stats.active_staff': 'Active Staff',
    'admin.stats.task_orders': 'Task Orders',
    'admin.stats.active_online': 'Online Personnel',
    'admin.stats.pending_tasks': 'Awaiting Action',
    'admin.stats.vs_last_month': 'vs last month',
    'admin.stats.from_last_month': 'from last month',

    'admin.user.management': 'User Management',
    'admin.user.management_sub': 'Manage access rights and verify field personnel.',
    'admin.activity.tariff_update': 'Tariff update pushed to South Basin',
    'admin.activity.tariff_desc': 'Admin Alex Seruyan adjusted base volumetric rates by +2% for industrial meters.',
    'admin.activity.new_staff': 'New Field Staff onboarded',
    'admin.activity.staff_desc': 'Siti Rahayu granted access to North Basin regional config and repair tickets.',
    'admin.user.table.name': 'Full Name',
    'admin.user.table.whatsapp': 'WhatsApp',
    'admin.user.table.role': 'Role',
    'admin.user.table.code': 'Verification Code',
    'admin.user.table.actions': 'Actions',
    'admin.user.details': 'Profile Details',
    'admin.user.table.identity': 'Account Identity',
    'admin.user.table.contact': 'Staff Contact',
    'admin.user.table.password': 'Access Password',
    'admin.user.table.role_status': 'Role & Status',
    'admin.user.table.v_actions': 'Verification Actions',
    'admin.user.add_new': 'Add New Account',
    'admin.user.msg.added': 'User added successfully',
    'admin.user.msg.status_updated': 'User status updated successfully',
    'admin.user.msg.status_error': 'Failed to update user status',
    'admin.user.button.activate': 'Activate Account',
    'admin.user.button.deactivate': 'Deactivate Account',

    'admin.tasks.management': 'Work Order List',
    'admin.tasks.management_sub': 'Real-time monitoring and assignment of field teams.',
    'admin.tasks.table.details': 'Task Details',
    'admin.tasks.table.reason': 'Description / Priority',
    'admin.tasks.table.assignee': 'Personnel',
    'admin.tasks.table.status': 'Status',
    'admin.tasks.table.actions': 'Actions',
    'admin.tasks.empty': 'No active work orders',
    'admin.tasks.routine': 'Routine Maintenance',
    'admin.tasks.unknown_staff': 'No Assignee Yet',
    'admin.tasks.unknown_customer': 'Walk-in / Unregistered',
    'admin.tasks.unassigned_tag': 'Unassigned',
    'admin.tasks.deadline.urgent': '24h Deadline',
    'admin.tasks.deadline.cycle': 'Cycle Schedule',

    'admin.sidebar.requests': 'New Requests',
    'admin.requests.title': 'New Connection Requests',
    'admin.requests.subtitle': 'Review and process new customer applications.',
    'admin.requests.table.details': 'Applicant Details',
    'admin.requests.table.contact': 'Contact Info',
    'admin.requests.table.date': 'Date Submitted',
    'admin.requests.table.status': 'Status',
    'admin.requests.table.actions': 'Actions',
    'admin.requests.empty': 'No pending requests.',
    'admin.requests.status.pending': 'Pending',
    'admin.requests.status.approved': 'Approved',
    'admin.requests.status.rejected': 'Rejected',
    'admin.requests.approve': 'Approve',
    'admin.requests.reject': 'Reject',

    // Admin Sub-components
    'admin.waterflow.title': 'Water Flow Monitoring',
    'admin.waterflow.subtitle': 'Real-time distribution and pressure analysis per sector.',
    'admin.waterflow.total': 'Total System Output',
    'admin.waterflow.stable': 'Flow Stable',
    'admin.waterflow.flow': 'Flow Rate',
    'admin.waterflow.pressure': 'Line Pressure',
    'admin.waterflow.zone.north': 'North Basin',
    'admin.waterflow.zone.central': 'Central District',
    'admin.waterflow.zone.west': 'West Sector',
    'admin.waterflow.zone.south': 'South Industrial',

    'admin.billing.title': 'Billing & Revenue',
    'admin.billing.subtitle': 'Manage financial transactions and customer billing cycles.',
    'admin.billing.monthly': 'Revenue This Month',
    'admin.billing.recent': 'Recent Transactions',
    'admin.billing.filter': 'Filter Data',

    // Admin Modals
    'admin.user.add_title': 'Create New Account',
    'admin.user.verified': 'Already Verified',
    'admin.user.label.name': 'Full Name',
    'admin.user.label.email': 'Email Address',
    'admin.user.label.phone': 'WhatsApp Number',
    'admin.user.label.password': 'Initial Password',
    'admin.user.label.role': 'System Role',
    'admin.user.role.customer': 'Customer',
    'admin.user.role.staff': 'Field Staff',
    'admin.user.button.cancel': 'Cancel',
    'admin.user.button.create': 'Confirm Account',
    'admin.user.button.creating': 'Processing...',

    'admin.tasks.not_found': 'Task not found',
    'admin.tasks.status.unassigned': 'Awaiting Assignment',
    'admin.tasks.priority.high': 'High Priority',
    'admin.tasks.priority.normal': 'Normal Priority',
    'admin.tasks.status.pending': 'Pending',
    'admin.tasks.status.assigned': 'Assigned',
    'admin.tasks.status.completed': 'Verified Completed',
    'admin.tasks.status.active': 'In Progress',
    'admin.tasks.add': 'Add Work Order',

    'admin.tasks.add_title': 'Create Work Order',
    'admin.tasks.label.type': 'Work Category',
    'admin.tasks.label.customer': 'Customer Data',
    'admin.tasks.label.location': 'Assignment Location',
    'admin.tasks.label.district': 'District / Zone',
    'admin.tasks.label.priority': 'Priority Level',
    'admin.tasks.label.staff': 'Select Staff (Optional)',
    'admin.tasks.label.reason': 'Notes / Reason',
    'admin.tasks.placeholder.location': 'e.g. Jl. Merdeka No. 5',
    'admin.tasks.placeholder.district': 'e.g. Seruyan Hilir',
    'admin.tasks.placeholder.reason_disconnect': 'e.g. Arrears over 3 months',
    'admin.tasks.placeholder.reason_leak': 'e.g. Main pipe leakage report',
    'admin.tasks.type.repair': 'Technical Repair',
    'admin.tasks.type.repair_prefix': 'Repair:',
    'admin.tasks.type.reading': 'Installation & Reading',
    'admin.tasks.type.reading_prefix': 'Meter:',
    'admin.tasks.type.disconnection': 'Disconnection',
    'admin.tasks.type.disconnection_prefix': 'Disconnection:',
    'admin.tasks.type.new_connection': 'New Connection',
    'admin.tasks.type.new_connection_prefix': 'New Conn:',
    'admin.tasks.select_customer': 'Search Customer...',
    'admin.tasks.unassigned': 'Suspend Assignment',

    // Staff Dashboard
    'staff.stats.today': 'Today',
    'staff.tasks.queue.repair': 'Repair Queue',
    'staff.tasks.queue.reading': 'Install & Readings',
    'staff.tasks.queue.disconnection': 'Disconnection Queue',
    'staff.tasks.work_orders': 'Work Orders',
    'staff.tasks.priority_tag': 'Priority',
    'staff.tasks.id': 'ID Number',
    'staff.tasks.verify_meter': 'Verify Meter No. {id} matches',
    'staff.tasks.warning_resident': 'Issue final verbal warning to resident',
    'staff.tasks.cycle.planned': 'Scheduled Cycle',
    'staff.tasks.deadline.by': 'Finish By',
    'staff.tasks.button.start': 'Start Work',
    'staff.tasks.empty.reading': 'No scheduled readings left',
    'staff.tasks.empty.generic': 'No tasks in this category',
    'staff.tasks.sop.title': 'Standard Procedure (SOP)',
    'staff.tasks.sop.subtitle': 'Security Protocol V.2',

    'staff.tabs.repair': 'Repairs',
    'staff.tabs.reading': 'Install & Read',
    'staff.tabs.disconnection': 'Disconnections',
    'staff.tabs.new_connection': 'New Connection',
    'staff.tasks.queue.new_connection': 'New Connection Queue',
    'staff.stats.daily_target': 'Task Capacity',
    'staff.stats.completed': 'Done',
    'staff.stats.pending': 'Awaiting',
    'staff.tasks.manual_reading': 'Manual Reading',
    'staff.profile.sector': 'Seruyan Sector',

    // Staff Reporting
    'staff.reading.title': 'Input Meter Reading',
    'staff.reading.subtitle.assigned': 'Reporting routine task.',
    'staff.reading.subtitle.manual': 'Self-input at customer site.',
    'staff.reading.search': 'Search ID or Name...',
    'staff.reading.success.title': 'Recorded!',
    'staff.reading.success.subtitle': '{name} meter reading sent to server.',
    'staff.reading.previous': 'Previous Value',
    'staff.reading.current': 'Current Value',
    'staff.reading.proof': 'Proof Photo',
    'staff.reading.capture': 'Take Meter Photo',
    'staff.reading.submit': 'Submit Report',
    'staff.reading.uploading': 'Sending...',

    'staff.disconnection.title': 'Execute Disconnection',
    'staff.disconnection.verify': 'Verify Task',
    'staff.disconnection.checklist': 'Field Checklist',
    'staff.disconnection.button.continue': 'Continue to Physical Action',
    'staff.disconnection.action.title': 'Technical Action',
    'staff.disconnection.action.subtitle': 'Seal and remove the customer meter.',
    'staff.disconnection.proof': 'Seal & Meter Photo',
    'staff.disconnection.notes': 'Staff Notes (Optional)',
    'staff.disconnection.submit': 'Submit Documentation',
    'staff.disconnection.confirm.title': 'Final Confirmation',
    'staff.disconnection.confirm.subtitle': 'Report will be permanently sent to the system.',
    'staff.disconnection.button.finalize': 'Finalize Task',
    'staff.disconnection.success.title': 'Task Completed!',
    'staff.disconnection.success.subtitle': 'Disconnection for {name} verified.',
    'staff.disconnection.return': 'Back to Home',

    // User Portal
    'user.balance.title': 'Current Bill',
    'user.balance.due': 'Due Date',
    'user.balance.pay': 'Pay Now',
    'user.stats.usage': 'Usage',
    'user.stats.efficiency': 'Efficiency',
    'staff.reading.prev': 'Previous Reading',
    'staff.reading.curr': 'Current Reading',
    'user.tabs.history': 'Billing History',
    'user.tabs.analysis': 'Usage Analysis',
    'user.billing.recent': 'Latest Bill',
    'user.billing.view_all': 'View All History',
    'user.billing.download': 'Download Invoice (PDF)',
    'user.usage.trend': 'Consumption Trend',
    'user.usage.ytd': 'Total Consumption (YTD)',
    'user.support.leak': 'Report Pipe Leak',
    'user.support.emergency': 'Emergency assistance 24/7',
    'user.bill.unit': 'm³',
    'user.bill.usage_label': 'Usage:',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('seruyan_lang') as Language) || 'id';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('seruyan_lang', newLang);
  };

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
